name: remote ssh command
on: 
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: github.actions.fabiotest.online
        username: fabio
        key: ${{ secrets.FABIO_SECRET_KEY }}
        port: 22
        script: whoami