name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: debian
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: github.actions.fabiotest.online
        username: fabio
        port: 22
        script: whoami